services:
    ratchet_app:
        class: Ratchet\App
        arguments:
            - chat.devel
            - 8080
            - 0.0.0.0

    chat.server:
        class: Touki\ChatBundle\Server
        arguments:
            - @ratchet_app
            - @chat.handler

    chat.handler:
        class: Touki\ChatBundle\ChatHandler
        arguments:
            - @chat.kernel

    chat.kernel:
        class: Touki\ChatBundle\Kernel
        arguments:
            - @chat.messenger
            - @chat.commandcontext_factory
            - @event_dispatcher
            - @chat.command_resolver
            - @chat.firewall

    chat.firewall:
        class: Touki\ChatBundle\Firewall
        arguments:
            - %chat.whitelist%

    chat.command_resolver:
        class: Touki\ChatBundle\CommandResolver

    chat.user_listener:
        class: Touki\ChatBundle\EventListener\UserListener
        arguments:
            - @chat.users
        tags:
            - { name: kernel.event_listener, event: command.pre_execute, method: onCommandPreExecute }

    chat.commandcontext_factory:
        class: Touki\ChatBundle\CommandContextFactory

    chat.messenger:
        class: Touki\ChatBundle\Messenger

    chat.users:
        class: Touki\ChatBundle\UserCollection

    chat.command.ima:
        class: Touki\ChatBundle\ChatCommand\Ima
        arguments:
            - @chat.users
        tags:
            - { name: chat.command }

    chat.command.msg:
        class: Touki\ChatBundle\ChatCommand\Message
        tags:
            - { name: chat.command }

    chat.command.bai:
        class: Touki\ChatBundle\ChatCommand\Bai
        tags:
            - { name: chat.command }

    chat.command.list:
        class: Touki\ChatBundle\ChatCommand\Users
        tags:
            - { name: chat.command }

    chat.command.kick:
        class: Touki\ChatBundle\ChatCommand\Kick
        tags:
            - { name: chat.command }
